version: '3.8'

services:
    app:
        image: php:8.2-fpm
        container_name: laravel_app
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        networks:
            - laravel
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
        depends_on:
            - db
        extra_hosts:
            - "host.docker.internal:host-gateway"
        # Gerekli PHP uzantılarını yüklemek için
        command: bash -c "apt-get update && apt-get install -y libpng-dev libjpeg-dev libfreetype6-dev && docker-php-ext-install pdo pdo_mysql mbstring exif pcntl bcmath gd"

    webserver:
        image: nginx:latest
        container_name: laravel_webserver
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel
        depends_on:
            - app

    db:
        image: mysql:8.0
        container_name: laravel_db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_DATABASE: magicport
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel


volumes:
    dbdata:
        driver: local

networks:
    laravel:
        driver: bridge
